FROM ruby:3.2.2-slim

# Install only what's needed
RUN apt-get update -qq && apt-get install -y build-essential

WORKDIR /app

# Copy the prometheus Gemfile and rename it to Gemfile for bundler
COPY Gemfile.prometheus ./Gemfile
RUN bundle config set --local without 'development test' && bundle install

EXPOSE 9394

CMD ["bundle", "exec", "prometheus_exporter", "-p", "9394", "-b", "0.0.0.0"]