FROM ruby:3.2.2-slim

# Install only what's needed
RUN apt-get update -qq && apt-get install -y build-essential

WORKDIR /app

# Copy the minimal Gemfile
COPY Gemfile.prometheus Gemfile.lock ./
RUN bundle install --without development test

EXPOSE 9394

CMD ["bundle", "exec", "prometheus_exporter", "-p", "9394", "-b", "0.0.0.0"]