# Use an official Ruby image as a parent image
FROM ruby:3.2.2-slim

# Install dependencies required for Rails and PostgreSQL
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn postgresql-client

# Install Foreman globally
RUN gem install foreman

# Set the working directory inside the container
WORKDIR /app

# Copy the Gemfile and Gemfile.lock into the container
COPY Gemfile* /app/

# Install any needed gems
RUN bundle install

# Copy the main application
COPY . /app

# Expose port 3000 to the outside world
EXPOSE 3000

# Start the main process (Rails server)
CMD ["./bin/dev"]
