default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: 5432
  database: signaux_faibles_v2_development
  username: postgres
  password: password

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
