default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: toto
  host: toto
  username: postgres
  password: toto

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
