default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: sfor_db_1
  port: 5433
  database: postgres
  username: postgres
  password: password

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
